openapi: 3.0.3
info:
  title: API - Sistema de Controle de Fluxos
  description: API para gerenciamento de usuários, equipamentos e fluxos de automóveis.
  version: 1.0.0

servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        email:
          type: string
        ativo:
          type: boolean
    Equipamento:
      type: object
      properties:
        id:
          type: integer
        codigo:
          type: string
        faixa:
          type: integer
        ativo:
          type: boolean
        integradorId:
          type: integer
    Fluxo:
      type: object
      properties:
        id:
          type: integer
        codigoEquipamento:
          type: string
        faixaEquipamento:
          type: integer
        dataHora:
          type: string
          format: date-time
        placa:
          type: string

security:
  - bearerAuth: []

paths:
  /users:
    get:
      summary: Listar usuários
      tags: [Usuários]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Lista de usuários
    post:
      summary: Criar novo usuário
      tags: [Usuários]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Usuário criado
    put:
      summary: Atualizar usuário
      tags: [Usuários]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: Usuário atualizado
    delete:
      summary: Deletar usuário
      tags: [Usuários]
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Usuário deletado

  /integradores:
    get:
      summary: Listar integradores
      tags: [Integradores]
      responses:
        200:
          description: Lista de integradores
    post:
      summary: Criar integrador
      tags: [Integradores]
      responses:
        201:
          description: Integrador criado
    put:
      summary: Atualizar integrador
      tags: [Integradores]
      responses:
        200:
          description: Integrador atualizado
    delete:
      summary: Deletar integrador
      tags: [Integradores]
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Integrador deletado

  /municipios:
    get:
      summary: Listar municípios
      tags: [Municípios]
      responses:
        200:
          description: Lista de municípios
    post:
      summary: Criar município
      tags: [Municípios]
      responses:
        201:
          description: Município criado
    put:
      summary: Atualizar município
      tags: [Municípios]
      responses:
        200:
          description: Município atualizado
    delete:
      summary: Deletar município
      tags: [Municípios]
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Município deletado

  /equipamentos:
    get:
      summary: Listar equipamentos
      tags: [Equipamentos]
      parameters:
        - name: codigo
          in: query
          schema:
            type: string
        - name: faixa
          in: query
          schema:
            type: integer
        - name: ativo
          in: query
          schema:
            type: boolean
        - name: integrador
          in: query
          schema:
            type: integer
      responses:
        200:
          description: Lista de equipamentos
    post:
      summary: Criar equipamento
      tags: [Equipamentos]
      responses:
        201:
          description: Equipamento criado
    put:
      summary: Atualizar equipamento
      tags: [Equipamentos]
      responses:
        200:
          description: Equipamento atualizado
    delete:
      summary: Deletar equipamento
      tags: [Equipamentos]
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Equipamento deletado

  /fluxos:
    get:
      summary: Listar fluxos
      tags: [Fluxos]
      parameters:
        - name: CodEquipamento
          in: query
          schema:
            type: string
        - name: faixaEquipamento
          in: query
          schema:
            type: integer
        - name: dataInicio
          in: query
          schema:
            type: string
            format: date
        - name: dataFim
          in: query
          schema:
            type: string
            format: date
        - name: HoraInicio
          in: query
          schema:
            type: string
            example: '08:00'
        - name: HoraFim
          in: query
          schema:
            type: string
            example: '18:00'
        - name: placa
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 30
      responses:
        200:
          description: Lista de fluxos (máximo de 30)
    post:
      summary: Registrar novo fluxo
      tags: [Fluxos]
      responses:
        201:
          description: Fluxo registrado
    put:
      summary: Atualizar fluxo
      tags: [Fluxos]
      responses:
        200:
          description: Fluxo atualizado
    delete:
      summary: Deletar fluxo
      tags: [Fluxos]
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Fluxo deletado
